;;; Color theme based on Tango Palette.
;;; Created by zhuqin <zhuqin83@gmail.com>

(defun color-theme-tango-light ()
  "A color theme based on Tango Palette."
  (interactive)
  (color-theme-install
   '(color-theme-tango-light
     ((background-color . "#ffffff")
      (background-mode . light)
      (border-color . "#eeeeec")
      (cursor-color . "#3465a4")
      (foreground-color . "#1a1a1a")
      (mouse-color . "#8ae234"))
     ((help-highlight-face . underline)
      (ibuffer-dired-buffer-face ((t (:foreground "#3465a4"))))
      (ibuffer-help-buffer-face . font-lock-comment-face)
      (ibuffer-hidden-buffer-face . font-lock-warning-face)
      (ibuffer-occur-match-face . font-lock-warning-face)
      (ibuffer-read-only-buffer-face ((t (:foreground "#75507b"))))
      (ibuffer-special-buffer-face . font-lock-keyword-face)
      (ibuffer-title-face . font-lock-type-face))
     (fringe ((t (:background "#eeeeec"))))
     (mode-line ((t (:foreground "#ffffff" :background "#3465a4" :box (:style released-button)))))
     (region ((t (:background "#fce94f"))))
     (font-latex-math-face ((t (:foreground "#8f5902"))))
     (font-latex-sedate-face ((t (:foreground "#204a87"))))
     ;; (font-latex-string-face ((t (:foreground "#4e9a06"))))
     (font-latex-warning-face ((t (:foreground "#ef2929" :bold t))))
     (font-lock-builtin-face ((t (:foreground "#3465a4"))))
     (font-lock-comment-face ((t (:foreground "#729fcf"))))
     (font-lock-constant-face ((t (:foreground "#c4a000" :bold t))))
     (font-lock-doc-face ((t (:foreground "#c17d11"))))
     ;; (font-lock-doc-string-face ((t (:foreground "mediumvioletred"))))
     (font-lock-keyword-face ((t (:foreground "#ce5c00" :bold t))))
     (font-lock-string-face ((t (:foreground "#75507b"))))
     (font-lock-type-face ((t (:foreground "#5c3566" :bold t))))
     (font-lock-variable-name-face ((t (:foreground "#4e9a06" :bold t))))
     (font-lock-warning-face ((t (:bold t :foreground "#ef2929"))))
     (font-lock-function-name-face ((t (:foreground "#3465a4" :bold t))))
     (comint-highlight-input ((t (:italic t :bold t))))
     (comint-highlight-prompt ((t (:foreground "#8ae234"))))
     (isearch ((t (:background "#f57900" :foreground "#2e3436"))))
     (isearch-lazy-highlight-face ((t (:background "#e9b96e" :foreground "#2e3436"))))
     (show-paren-match-face ((t (:background "#73d216"))))
     (show-paren-mismatch-face ((t (:background "#ad7fa8" :foreground "#2e3436"))))
     (minibuffer-prompt ((t (:foreground "#3465a4" :bold t))))
     (info-xref ((t (:foreground "#3465a4"))))
     (info-xref-visited ((t (:foreground "#75507b"))))
     (highlight ((t (:background "#d3d7cf"))))
     )))

(provide 'color-theme-tango-light)
